### ISSUE TITLE
VoxelShape#unionCoversFullCube is too slow

### ISSUE THREAD

**Issue by Spottedleaf** [Tuinity/Starlight#3]
Need to port https://github.com/Spottedleaf/Tuinity/blob/dev/lighting/patches/server/0058-fixup-Highly-optimise-single-and-multi-AABB-VoxelSha.patch#L628-L670
Affects mainly snowy areas

**Comment by ghost** [comment]
hey can you tell me when this could be implemented? thanks
and also why paperspigot is superior 🤡

**Comment by katekerllenevich** [comment]
eww guys we have a 1.8 nerd over here lol
paperspigot is 1.8

**Comment by iiisak** [comment]
Link is dead since the dev/lightning branch got merged but https://github.com/Spottedleaf/Tuinity/blob/master/patches/server/0025-Highly-optimise-single-and-multi-AABB-VoxelShapes-an.patch could be what he meant
